### ISSUE TITLE
SinglePlayerMenu UI Broken

### ISSUE THREAD

**Issue by Chaos192** [Paldamar/UE4_CommandAndConquer_FAN_GAME#1]
![image](https://user-images.githubusercontent.com/9710259/69765131-f765cb00-112f-11ea-957e-9dd353cc07ec.png)

any suggestions to fix?

**Comment by IanWigle** [comment]
Yeah I know where this issue comes from. I am currently doing some refactoring so some links are currently needing to be fixed. I am not near a computer. Those details are related to the lobby system that is not fully implemented.

**Comment by IanWigle** [comment]
Fixed in newest commit e5ddcfc3c3049ff1921969cc65a437b06e8e5f80
